In [1]:
import numpy as np #as Para definir un acronimo y no escribir la palabr numpay completa
from numpy import *  #Asi importamos todas las librerias de numpay

In [3]:
miLista=[1,2,3,4,5,6,7,8]  #Definicion de una lista

In [5]:
#Convertimos la lista en un array de datos con el metodo np.array()
np1=np.array(miLista)
np1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
#Podemos definir tambien el tipo de dato en un array 
np2=np.array(miLista,dtype='float32')
np2  #Ahora en un array de numeros decimales

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

In [10]:
#Tipos de datos en un array
#- bool
#- int_ = de 32 o 64 bits
#- intc = entero long en C
#- intp = para indexar 
#- int8 = enteros de 8 bits de -128 hasta 127
#- int16 = entero de 16 bits de -32768 hasta 32767
#- int32 = entero de 32 bits de -2mil millones hasta 2 mil millnes
#- int64 = entero de 64 bits de -9x10E18
#- uint8 = entero sin signo 0 hasta 255
#- uint16 = entro sin signo desde 0 hasta 65535
#- uint32 = entro sin signo desde 0 hasta 4mil millones
#- uint64 = entro sin signo desde 0 hasta 18X10e18
#- float_ = float64 maxima precisioon
#- float16 = media precicion 1bit signo-5bit exp-10bit valores numerico (+/-9999999999e99999)
#- float32 = media precicion 1bit signo-8bit exp-23bit valores numerico
#- float64 = doble 1bit signo 11bit exp-52bit valores numerico
#- complex_= numeros complejos de 64bits
#- complex64= numeros complejos 32 parte real/32 parte imaginaria
#- complex128= nnumeros complejos 64 parte real/64 parte imaginaria 

In [222]:
#Creamos un array de ceros de nfilas por ncolumnas
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [223]:
#Creamos un array de unos de nfilas por ncolumnas
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [224]:
np.arange(10) #Define un array con 10  elementos y una sola fila

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#Creamos un array de datos en un rango de 3:12 y de tipo de dato float
np.arange(3,12,dtype='float')

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [20]:
#Creamos un array de datos en un rango del inicio en 4:5  con saltos de 0.1 hasta llegar al 5
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [22]:
#array de numeros que inicia en 1:7 con 12 num difernetes, con la funcion linspace
np.linspace(1,7,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [24]:
# La funcion eye() permite definir una matriz de identidad, que en la diagonal tiene 1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
x=np.zeros((8,3))  #La funcion zeros define una matriz de 8 filas por 3 columnas
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
x.reshape((6,4))  #Redefine la matriz de elementos

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
x1=np.arange(24)
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [41]:
x1.reshape((3,8))#redefinimos la matriz a una de 3x8

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [42]:
# ravel regresa el mismo array en forma unidimencional
x=np.array([ [1,2,3,4] ,[1,2,3,4,] ])
x

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [43]:
np.ravel(x) #Con esta funcion aplanamos el array original sin importar las filas y columnas

array([1, 2, 3, 4, 1, 2, 3, 4])

In [45]:
#Regresa una copia del array colpsado, no es el array original
x.flatten()

array([1, 2, 3, 4, 1, 2, 3, 4])

In [46]:
# Transponer un array con la funcion transpose()
np.transpose(x)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [50]:
#Rezise, crea un array dedatos apartir del array original y redefinido por una nueva dimension 
np.resize(x,(5,3))

array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1],
       [2, 3, 4],
       [1, 2, 3]])

# Ejercicios con arreglos
#1.Array de datos con valores entre 5 y 120
#2.Matriz de 4x4 con valores de 0 hasta 15
#3.Matriz de identidad 7X7
#4.Crear un array de 20 elementos y transformalos en una matriz de 5x4
#5.crear un array de 20 numeros con valores entre 0 y 5 espaciados de forma uniforme

In [54]:
array1=np.arange(5,120)
array1

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [66]:
array2=np.arange(0,16)
array2.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
array3=np.eye(7)
array3

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [72]:
array4=np.arange(0,20)
array4.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [75]:
array5=np.linspace(0,5,20)
array5

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

# Propiedades de un array

In [95]:
x=np.arange(0,12)
x=np.reshape(x,(3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
#La propiedad ndim indica cuantas dimenciones tiene el array
x.ndim   

2

In [88]:
#La propiedad shape indica las dimencion en filas x Columnas en este caso es de 3Fx4C
x.shape

(3, 4)

In [90]:
#La propiedad Zise Es el numero total de elementos del array
x.size 

12

In [91]:
#La propiedad dtype indica el tipo de dato del array
x.dtype

dtype('int32')

In [97]:
#La propiedad itemsize indica cuantos bits ocupan cada uno de los elemtos de la matriz
x.itemsize

4

In [99]:
#La propiedad data indicala posicion del elemento en memoria
x.data

In [103]:
x[2]   #Para acceder a toda la fila 2
x[2,1] #Para acceder a una posicion en especifico

9

In [106]:
x.shape=(4,3)   #Permite redefinir la matriz a una nueva dimecion es similar a reshape
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [107]:
x[1:3,0:2] #Extrae un sub array el original (de forma excluyente segun los argumentos)

array([[3, 4],
       [6, 7]])

In [110]:
y=np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [112]:
y[3:5]   #Extrae un sub array excluyente de una matriz de una dimencion

array([3, 4])

In [116]:
y[1:7:2] #Extrae un sub array excluyente de una matriz con saltos de 2 posiciones 

array([1, 3, 5])

In [119]:
z=np.arange(10,6,-1)  #Funcion arange para genear un array con elementos de 10:6, pero el tercer parametro con saltos -1
z

array([10,  9,  8,  7])

In [121]:
y[z]  #Acceder a valores de un array por medio de otro array

array([10,  9,  8,  7])

In [124]:
x=np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [126]:
x[x>30]   #Solo muestra los valores del array que son mayores a 30

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [130]:
cond= (x < 25)   #Solo muestra los que cumplan la condicion logica 
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [132]:
x[cond]   #Consultamos los valores boleanos segun los valores de cond

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [134]:
x[12:24]=1 #De la posicion 12 a la 24 se asigna el valor 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [137]:
x[13:16]=[6,9,12]   #Otro ejemplo de como acceder a una serie de posiciones y asignarle una array de valores
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [139]:
#Los tipos de datos son homogenios, no se puede ajustar como en una lista
x[1]=3.1415
x

array([ 0,  3,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Copias y vistas de array

In [144]:
miArray=np.arange(10)
miArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
y=miArray #ESTO NO ES UNA COPIA, ES UNA REFERENCIA DEL ARRAY ORIGINAL, SI SE MODIFICA "Y", SE ACTUALIZA "MIARRAY" 
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
y.shape=(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [153]:
miArray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [157]:
z=miArray.copy()   #Creamos una copia del array por medio de la funcion copy(), de esta forma deja de ser una referencia
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [159]:
z is miArray   #No es igual por que es una copia en este caso es False

False

In [161]:
y is miArray #Es True por que es una referencia de miArray, en este caso es lo mismo

True

In [163]:
t=z.view() #Con la funcion vista podemos hacer una "Copia" del array donde comparte valores pero no propiedades
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [164]:
t[:]=10   #A la vista array "t" ,todo el contenido se le asigna 10, por lo que se modifica el contenido
t

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# Funciones Universales(ufunc)
- Permite aplicar operciones a los array sin tener que aplica sentencias como for o while
- unarias: Operaciones que se aplican elemento a elemento : sqrt, sin,cos, **2
- binarias: Operaciones que reciben 2 array y debuelven un unico array, maximum, minimum

In [180]:
miArray2=np.arange(10,20)
miArray2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [172]:
miArray2+5  #Ejemplo de operacion Unaria

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [174]:
miArray2*2  #Ejemplo de operacion Unaria

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [177]:
miArray2=np.linspace(1,2*np.pi,7)   #Aplioca la operacion 2*np.pi del elemento 1:7
miArray2

array([1.        , 1.88053088, 2.76106177, 3.64159265, 4.52212354,
       5.40265442, 6.28318531])

In [182]:
np.sin(miArray2)

array([-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [184]:
np.cos(miArray2)

array([-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [186]:
np.exp(miArray2)

array([2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08])

In [191]:
np.power(miArray2,2)  #Para elevar cada elemento a la potencia 2

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [193]:
np.power(3,miArray2)  #Para elevar el numero 3 elevada a cada elemento del array como potencia

array([     59049,     177147,     531441,    1594323,    4782969,
         14348907,   43046721,  129140163,  387420489, 1162261467],
      dtype=int32)

In [194]:
np.sum(miArray2)    #Regresa la suma de todos los elementos sumados del array

145

In [ ]:
#Existen la operaciones para trabajar con valoes NAN= not at null (valores vacios o que no estan definidos)

In [196]:
np.nansum(miArray2)

145

In [197]:
np.nanprod(miArray2)  # El producto de todos los valores del array

213837312

In [198]:
np.argmin(miArray2)  #Regresa la posicion donde se encuentra el valor mas pequeño

0

In [199]:
np.argmax(miArray2) #Regreas la posicion dende se encuentra el valor mas grande el array

9

In [200]:
np.percentile(miArray2,10)  #Para calcular el percentil del array total

10.9

In [203]:
arrayAny=np.array([True,False,True])
np.any(arrayAny)  #Regresa True si alguno de los valores en True

True

In [205]:
np.all(arrayAny)  #Regresa True si todos son True

False

In [206]:
arrayAny=np.array([True,True,True])
np.any(arrayAny)  #Regresa True si alguno de los valores en True

True

In [209]:
#Definimos un array aleatorio de dimension 3x3
miArrayRan= np.random.random((3,3))
miArrayRan

array([[0.22470031, 0.93934097, 0.89625671],
       [0.37347019, 0.4917325 , 0.17702478],
       [0.35743057, 0.93447717, 0.09657701]])

In [210]:
np.sum(miArrayRan)

4.491010203817191

In [212]:
np.sum(miArrayRan,axis=0)   #Para sumar los datos por columnas

array([0.95560107, 2.36555063, 1.1698585 ])

In [213]:
np.sum(miArrayRan,axis=1)   #Regreasa el total de la suma por filas 

array([2.06029799, 1.04222746, 1.38848475])

In [225]:
np.random.seed(10)  #EL metodo seed (semilla) permite fijar un numero para que los valores random sean seudo aleatorios
miArrayRan= np.random.random((3,3))
miArrayRan

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

# Algebra lineal con python

In [233]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[3,0],[1,-1]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[ 3  0]
 [ 1 -1]]


In [238]:
A+B  #Sumamos las matrices

array([[4, 2],
       [4, 3]])

In [253]:
A.dot(B)  # Muultiplicar dos matrices don la funcion dot(<matriz>)

array([[ 5, -2],
       [13, -4]])

In [241]:
A.transpose()   #Trasponer un array

array([[1, 3],
       [2, 4]])

In [242]:
np.linalg.matrix_rank(A)    #Calcula el rango de una matriz

2

In [244]:
np.linalg.matrix_power(A,5)

array([[1069, 1558],
       [2337, 3406]])

In [245]:
np.linalg.det(A)

-2.0000000000000004

In [246]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [247]:
C=np.array([[1,2,3],[4,5,6],[7,8,9,]])
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [250]:
np.linalg.det(C)

6.66133814775094e-16

In [251]:
np.linalg.matrix_rank(C)

2

In [252]:
np.linalg.inv(C)   #Si la matriz tiene un rango menor a su orden , entonces no es inv

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])